str1 = input("Enter first string: ")
str2 = input("Enter second string: ")
combined_str = str1 + str2
print("\nConcatenated String:", combined_str)
print("\nString Methods Applied:")
print("lower():", combined_str.lower())
print("upper():", combined_str.upper())
print("title():", combined_str.title())
print("swapcase():", combined_str.swapcase())
print("capitalize():", combined_str.capitalize())
print("casefold():", combined_str.casefold())
print("center(30):", combined_str.center(30))
print("count('a'):", combined_str.count('a'))
print("endswith('!'):", combined_str.endswith('!'))
print("find('a'):", combined_str.find('a'))
print("isalnum():", combined_str.isalnum())
print("isdigit():", combined_str.isdigit())
print("isnumeric():", combined_str.isnumeric())
print("isspace():", combined_str.isspace())
print("replace('a', '*'):", combined_str.replace('a', '*'))